version: '3'

services:
  server:
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - ALLOW_IP_RANGE=0.0.0.0/0
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: on-failure