version: '3'

services:
  server:
    build: ./
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database
  database:
    container_name: postgres_db
    image: postgres:9.6
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432